### ISSUE TITLE
Calendar Entries

### ISSUE THREAD

**Issue by t12nslookup** [verdammelt/tnef#13]
We have 2 companies under the same umbrella, one of them uses Outlook and Exchange, the other uses Sendmail/Dovecot and combinations of Non-Outlook clients.

The Admin Assistant always sends calendar invites from her Outlook, which stores the invites in a winmail.dat file, and sends them to our Director, who cannot open them.

we use TNEF to extract all attachments, but it is not recognising the Calendar entries embedded in the file

I have a winmail.dat file with calendar entries embedded, if you would like to have a look.

**Comment by MattHall** [comment]
I too am seeing this issue. I have a winmail.dat that contains an .ics file, and although I can retrieve it using a different app (http://www.joshjacob.com/mac-development/tnef.php), it's not returned when running `tnef`.

@t12nslookup Did you find a way around this issue?

**Comment by t12nslookup** [comment]
Simplest way was to make sure everyone is using latest Thunderbird with the latest lightning plugin ... Which means overriding the default application on Mac and PC, as well as Linux/Solaris.  Doesn't food the original issue though.

**Comment by MattHall** [comment]
Thanks @t12nslookup - I'm going to contact @verdammelt directly (per the BUGS file) as the file I'm working with is sensitive.

**Comment by verdammelt** [comment]
I received the data file from @MattHall  and it does *not* contain an ICS file. It *may* contain data which could be interpreted as a calendar request. TNEF does nothing which such data as it's purpose is to extract files contained in MS-TNEF encoded attachments.

**Comment by MattHall** [comment]
As per @verdammelt's comment above, I'm not really sure how the data is encoded, but using (TNEF's Enough)(http://www.joshjacob.com/mac-development/tnef.php) on the winmail.dat file does find an ics file, so it looks like it has been added to the winmail.dat using some other method than as an attachment, though I'm not certain how yet.

**Comment by MattHall** [comment]
So it appears that TNEF's Enough is creating the ics based on the information encoded under message and MAPI properties in the file. 

@t12nslookup When you say you had "a winmail.dat file with calendar entries embedded", do you mean the attributes were embedded as a MAPI object properties?

**Comment by t12nslookup** [comment]
Embedded as a mapi, I believe.

**Comment by verdammelt** [comment]
Closing as stale. (sorry)

**Comment by sagariosdev** [comment]
@verdammelt Any update related to .ics file?

**Comment by verdammelt** [comment]
@sagariosdev no. I am not doing any active development on this project. I have no current plans to add new features such as creation of ics files.
