### ISSUE TITLE
1.4.13 release

### ISSUE THREAD

**Issue by 0-wiz-0** [verdammelt/tnef#16]
There are commits that have the commit message 'release 1.4.13' but there is no actual tag/release. Can you please make one?

**Comment by verdammelt** [comment]
I knew I forgot something! :(

Done.

**Comment by 0-wiz-0** [comment]
Thanks, that was quick.
One thing to consider: a plain tag like you have now just gives you the state of the repository; in other words, the generated files from autoconf/automake are not included.
Github allows uploading complete distfiles for a release, so that's a manual step one needs to do when releasing auto*-using software.

**Comment by verdammelt** [comment]
Possibly a useful idea. I'll look into it for next time thanks.
