### ISSUE TITLE
Attached winmail.dat is different on Outlook and on tnef decoder

### ISSUE THREAD

**Issue by amirashad** [verdammelt/tnef#25]
Third attachment in this winmail.dat is Ryanair Travel Itinerary, which is not same with Outlook. 
What would be the reason? And how to parse it successfully?
[winmail.dat.zip](https://github.com/verdammelt/tnef/files/1132979/winmail.dat.zip)
Thanks.

**Comment by verdammelt** [comment]
It appears that the final document in the `winmail.dat` file is tagged as `message/rfc822` which I would interpret as simply "an email message". However it is not in plain text and my system can't identify what type of file it might be.

Perhaps it is in a format which Outlook recognizes and then interprets correctly.

You say what you get from `tnef` is not the same as with Outlook. What is the difference?

**Comment by amirashad** [comment]
Thanks for your answer. 
I exported third file from Outlook. This file is viewable via Outlook. Also file size is 62KB which is differ from ours (40KB).
Is there any other way to extract that file properly?
[Ryanair Travel Itinerary-outlook.msg.zip](https://github.com/verdammelt/tnef/files/1134486/Ryanair.Travel.Itinerary-outlook.msg.zip)

**Comment by verdammelt** [comment]
No sorry I don't know another way to export it.

**Comment by amirashad** [comment]
Ok, Thanks a lot!

**Comment by verdammelt** [comment]
Sorry I could not be of more help.
