### ISSUE TITLE
Chinese name issue

### ISSUE THREAD

**Issue by witwall** [verdammelt/tnef#28]
if attachments named in Chinese, would not get the right name,

here is the output files name when run ```tnef winmail.dat```
```
C%C0%E0%CE%EF%C1%CF1.xls  
C%C0%E0%CE%EF%C1%CF2.xlsx 
D%C0%E0%CE%EF%C1%CF.xls
```

and here is the right name when run ```tnef -t winmail.dat```

btw, I am using Mac OS X

**Comment by verdammelt** [comment]
@witwall thanks for the report. To investigate I'll need a datafile that illustrates this problem. Can you attach one here or email one to me?

Also your report shows how things are wrong with `tnef -t winmail.dat` but then you say it has "right name" with the same command? Please clarify.

**Comment by witwall** [comment]
sorry, my typo, wrong with extract, but right with -t(just show name).

and I will send you a sample.

**Comment by jidanni** [comment]
Here's one.
[winmail.dat.gz](https://github.com/verdammelt/tnef/files/1528811/winmail.dat.gz)
Apparently the filenames are in **big5**, which create gobbeldygook filenames when extracted on a UTF-8 system.

**Comment by verdammelt** [comment]
I haven't looked at the data file; but any ideas how one would know what encoding the filenames are in?

**Comment by witwall** [comment]
./tnef -t winmail.dat>list.txt

open list.txt with vcode, it should be big5, but still have wrong characters.

![image](https://user-images.githubusercontent.com/3222056/33594356-8af87e76-d9ce-11e7-8d35-b9479a1e348a.png)

**Comment by witwall** [comment]
[winmail.gbk.zip](https://github.com/verdammelt/tnef/files/1530020/winmail.gbk.zip)
and here is my GBK version example,
```
#with correct encoding
./tnef -t winmail.dat>list.txt  
```
![image](https://user-images.githubusercontent.com/3222056/33594663-ba4696e4-d9cf-11e7-933b-c5cf4d4e34f5.png)

**Comment by jidanni** [comment]
Also consider many users will be extracting on UTF-8 systems and it would be nice to convert the filenames by default. And only leave them raw if an option is given.

**Comment by verdammelt** [comment]
Thanks for all the info. Full disclosure: I am not going to take much, if any, time to look into this until the very end of they year when I have some time off. No guarantees that I will even release anything to fix this issue.

**Comment by jidanni** [comment]
OK. I don't get such files often.  By the way I notice wget has
       --local-encoding=encoding
       --remote-encoding=encoding

**Comment by verdammelt** [comment]
Regretfully I am going to not fix this issue and close it.

I do not feel I have the time & energy to properly handle code pages in TNEF. I am open to reviewing any patches to add such features.

I will be adding a little special debugging output so that CodePage data is easier for anyone to identify and I will update the README & man page to make it clear that TNEF makes assumption about the data being in some Unicode encoding.

Sorry @witwall & @jidanni . Thanks for submitting this issue and the work you've put into it.
