### ISSUE TITLE
On manpage warn of massive --debug output

### ISSUE THREAD

**Issue by jidanni** [verdammelt/tnef#31]
On the manpage at
```
       --debug
              enable debug output.
```
do add a warning that this will alas spew five times the
entire file's worth of bytes upon the screen.
```
$ ls -og winmail.dat
-rw------- 1 996334 12-05 01:27 winmail.dat
$ tnef --debug --list winmail.dat | wc
    337 1002968 5018665
```
So add that if the user is not prepared for five megbytes "in the face" he
should at least "pipe it to more(1)".

**Comment by verdammelt** [comment]
Well it *is* a debug log :)

But point taken; I'll add your recommended warning.
