### ISSUE TITLE
On manpage clarify --save-body FILE

### ISSUE THREAD

**Issue by jidanni** [verdammelt/tnef#32]
On the manpage at
```       --save-body FILE
              Save message body data found in the TNEF data. There can
```
mention if without --save-body will the message body data be saved
anyway or not.
```
              be up to three message bodies in the file, plain text,
              HTML encoded, and RTF encoded. Which are saved is
              specified by the --body-pref option. By default the
              message bodies are written to a file named message with
              an extension based upon the type (txt, html, rtf).
```
So maybe there is always an implicit ```--save-body message``` turned
on, and ```--save-body FILE``` just picks a new name instead of ```message```.
All this needs to be clarified on the man page.

**Comment by verdammelt** [comment]
The body of the message is separate from any files contained in the TNEF. It would be the contents of the email message the files were attached to.

I'll try to make this clearer in the document.
