### ISSUE TITLE
On manpage fix OTHER REFERENCES broken URL

### ISSUE THREAD

**Issue by LAMurakami** [verdammelt/tnef#36]
The tnef man page OTHER REFERENCES points to an old URL that no longer has content related to tnef: http://support.microsoft.com/support/kb/articles/Q136/2/04.asp

I would suggest you replace the MS support reference that is broken with the David A. Wheeler essay at: https://www.dwheeler.com/essays/microsoft-outlook-tnef.html

**Comment by verdammelt** [comment]
Thanks.

**Comment by david-a-wheeler** [comment]
FYI, I updated my page at <https://www.dwheeler.com/essays/microsoft-outlook-tnef.html>.

**Comment by verdammelt** [comment]
@david-a-wheeler cool and luckily the URL I changed the man page too is still valid! :)
