### ISSUE TITLE
Wrong version info for 1.4.16

### ISSUE THREAD

**Issue by mnadvornik** [verdammelt/tnef#37]
Hi,
it seems like you forgot to change the version info for the -V parameter. In two files there is still the old version:
https://github.com/verdammelt/tnef/blob/2a3790b892e307b13bba61ae882509efcbaa96ae/tests/cmdline/version.baseline#L2
https://github.com/verdammelt/tnef/blob/2a3790b892e307b13bba61ae882509efcbaa96ae/configure.ac#L2

Took me some time to figure out why the hell there is sill the old version shown after updating :)

**Comment by verdammelt** [comment]
Oh... this is super embarassing. :(

Thanks for catching it. I'll get a *new* version out this weekend.


Thanks again.
