### ISSUE TITLE
tnef fails to decode french characters correctly

### ISSUE THREAD

**Issue by ferdiga** [verdammelt/tnef#46]
opening a winmail.dat from a french sender, a wrong charset is used.
for example
https://www.winmail-dat.com/online.php
opens the winmail.dat with the correct data set

**Comment by verdammelt** [comment]
Thank you for the issue report. It sounds like the code in tnef for unpacking utf-8 is likely to be the problem. Eitehr it has a bug or perhaps we should not be doing it in this case?

That being said: I will not have the time to look into this any time soon. Sorry.

**Comment by verdammelt** [comment]
I am closing this issue. I will not be doing any work to improve this.
